name = "my_cicd"
version = "0.1.0"

[dependencies]
cicd = "0.10.0"
distrib = "0.10.0"
fs = "0.10.0"
http = "0.10.0"
net = "0.10.0"
process = "0.10.0"
std = "0.10.0"
work = "0.10.0"

[entrypoints]
advanced = "my_cicd/advanced::main"
main = "my_cicd::main"
